# This is a basic workflow to help you get started with Actions

name: Salesforce Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
     # Install SFDX CLI   
      - name: Install SFDX CLI
        run: npm install sfdx-cli --global
        
       # Authorize SF Org
      - name: Authorize SF Org
        run: sfdx force:auth:jwt:grant --clientid 3MVG9fe4g9fhX0E5Vqngh_xXhhA_kaPnWHnvD6VQc7ZiEK8uxAXvxdDOW7ti7LiKepSZG.o8mf6uVM4C2Lze5 --jwtkeyfile ./buildfiles/server.key --username irene@suyati.com --instanceurl https://login.salesforce.com

       # Convert to Deploy Source
      - name: Convert to Deploy Source
        run: sfdx force:source:convert -r ./force-app -d ./toDeploy
    
    # Run Validation of Deploy Source
      - name: Run Validation on Deploy Source
        run: sfdx force:source:deploy -c -x manifest/package.xml -u  irene@suyati.com
    
    # Deploy
      - name : Deploy to SF Org
      - if: ${{github.event_name == 'push'}}
        run: sfdx force:source:deploy -x manifest/package.xml -u irene@suyati.com 
 
